# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Food.create!(type: "Starters", cost: rand(9..18), name: "Stuffed Mushrooms")
Food.create!(type: "Starters", cost: rand(9..18), name: "Coconut Shrimp")
Food.create!(type: "Starters", cost: rand(9..18), name: "Bruschetta")
Food.create!(type: "Starters", cost: rand(9..18), name: "Cajun Calamari")
Food.create!(type: "Starters", cost: rand(9..18), name: "Idaho Nacho's")
Food.create!(type: "Starters", cost: rand(9..18), name: "Artichoke Dip")
Food.create!(type: "Starters", cost: rand(9..18), name: "Gumbo Ya-Ya")
Food.create!(type: "Salads", cost: rand(12..21), name: "Spinach Salad")
Food.create!(type: "Salads", cost: rand(12..21), name: "Dottie Salad")
Food.create!(type: "Salads", cost: rand(12..21), name: "Mediterranean Salad")
Food.create!(type: "Salads", cost: rand(12..21), name: "Fried Chicken Salad")
Food.create!(type: "Salads", cost: rand(12..21), name: "Annie's Steak Salad")
Food.create!(type: "Salads", cost: rand(12..21), name: "Classic Caesar")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Greek Lemon Chicken")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Key West Chicken")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Broiled Catfish")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Pasta Primavera")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Comfort Zone")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Chicken Fried Steak")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Chicken Vesuvio")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Chicken Parmesan")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Fettuccine Alfredo")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Lumberjack Steak")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Southern Specialties")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Chicken Savannah")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Chicken Murphy")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Chicken Savannah")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Marinated Salmon")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Shrimp Carolina")
Food.create!(type: "Main Course", cost: rand(17..27), name: "Patton Chapel Pasta")
Food.create!(type: "Dessert", cost: rand(30..40), name: "Magnolia's Assorted Cheesecake")
Food.create!(type: "Dessert", cost: rand(30..40), name: "Caribbean Key Lime Pie")
Food.create!(type: "Dessert", cost: rand(30..40), name: "Crazy Fried Apple Pie")
Food.create!(type: "Dessert", cost: rand(30..40), name: "Truckload of Chocolate")


Food.create!(type: "Soft Drink", cost: 1, name: "Coke")
Food.create!(type: "Soft Drink", cost: 1, name: "Diet Coke")
Food.create!(type: "Soft Drink", cost: 1, name: "Sprite")
Food.create!(type: "Soft Drink", cost: 1, name: "Mellow Yellow")
Food.create!(type: "Soft Drink", cost: 1, name: "Rootbeer")

Food.create!(type: "Beverage", cost: rand(1..5), name: "Fresh Brewed Coffee")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Mint Tea")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Decaf Iced Tea")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Chai Tea")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Smoothies")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Kiddie Cocktail")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Rootbeer Float")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Milk/Chocolate")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Orange")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Cranberry")
Food.create!(type: "Beverage", cost: rand(1..5), name: "Pineapple")

Waiter.create!(name: "Mark Ruff", salary: 13)
Waiter.create!(name: "John Spacey", salary: 13)

Table.create!(occupied: false)
Table.create!(occupied: false)
Table.create!(occupied: false)
Table.create!(occupied: false)
Table.create!(occupied: false)